### ISSUE TITLE
Interfaz gráfica descuadrada en Mi A1

### ISSUE THREAD

**Issue by raulrhs** [UNIZAR-30226-2020-09/FE-Android#47]
Además de las pantallas que adjunto, estaría bien que en las pantallas de crear contraseña, al menos el botón "continuar" estuviera siempre en el mismo sitio (está siempre abajo a la derecha, pero a la misma altura e refiero)
![WhatsApp Image 2020-04-18 at 14 51 48](https://user-images.githubusercontent.com/41389217/79638181-95f8d400-8184-11ea-937d-deb04ca5a70c.jpeg)
![WhatsApp Image 2020-04-18 at 14 51 49 (1)](https://user-images.githubusercontent.com/41389217/79638183-972a0100-8184-11ea-9731-ad228eb91963.jpeg)
![WhatsApp Image 2020-04-18 at 14 51 49](https://user-images.githubusercontent.com/41389217/79638184-972a0100-8184-11ea-9796-52068c5bb65a.jpeg)
![WhatsApp Image 2020-04-18 at 14 51 48 (1)](https://user-images.githubusercontent.com/41389217/79638185-97c29780-8184-11ea-8e54-38ab24d0d81b.jpeg)

**Comment by rauljavierre** [comment]
A qué te refieres con "pantallas de grupo"? @raulrhs 🤔
