### ISSUE TITLE
Navigacion desde la primera pantalla de Crear contraseña o Crear categoria hacia atrás

### ISSUE THREAD

**Issue by raulrhs** [UNIZAR-30226-2020-09/FE-Android#48]
Desde la primera pantalla de Crear contraseña o Crear categoría, si le das al botón de retorno del móvil, te saca de la app en lugar de devolverte al menú principal donde se listan las contraseñas.

**Comment by rauljavierre** [comment]
Eso lo soluciono en un momento 👍🏼
